all:
	g++ soft.c -o cajipciSOFTTRG
	g++ config.c -o cajipciCONFIGTRG
	g++ stat.c -o cajipciTRGSTAT
clean:
	rm -rf cajipciSOFTTRG cajipciCONFIGTRG cajipciTRGSTAT

intstall:
	cp cajipci* /usr/local/bin
